#!/usr/bin/env python3
"""
miner.py — Files everything into the palace.

Reads swampcastle.yaml from the project directory to know the wing + rooms.
Routes each file to the right room based on content.
Stores verbatim chunks as drawers. No summaries. Ever.
"""

import fnmatch
import hashlib
import inspect
import logging
import multiprocessing
import os
import re
import sys
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor, as_completed
from concurrent.futures.process import BrokenProcessPool
from datetime import datetime
from pathlib import Path

from ..project_config import PROJECT_CONFIG_NAME, resolve_project_config
from ..settings import CastleSettings
from ..storage import StorageFactory, factory_from_settings
from ..tuning import suggest_onnx_tuning
from .contributor import detect_contributor
from .kg_extract import persist_kg_proposals_for_wing
from .skeleton import get_skeleton_extractor

logger = logging.getLogger("swampcastle.mining.miner")

SKIP_DIRS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    "dist",
    "build",
    ".next",
    "coverage",
    ".swampcastle",
    ".ruff_cache",
    ".mypy_cache",
    ".pytest_cache",
    ".cache",
    ".tox",
    ".nox",
    ".idea",
    ".vscode",
    ".ipynb_checkpoints",
    ".eggs",
    "htmlcov",
    "target",
}


def _file_already_mined(
    collection,
    source_file: str,
    *,
    wing: str | None = None,
    check_mtime: bool = False,
) -> bool:
    try:
        where = {"source_file": source_file}
        if wing is not None:
            where = {"$and": [{"source_file": source_file}, {"wing": wing}]}
        results = collection.get(where=where, limit=1)
        if not results.get("ids"):
            return False
        if check_mtime:
            stored_meta = results.get("metadatas", [{}])[0]
            stored_mtime = stored_meta.get("source_mtime")
            if stored_mtime is None:
                return False
            current_mtime = os.path.getmtime(source_file)
            return abs(float(stored_mtime) - current_mtime) < 0.001
        return True
    except Exception:
        return False


READABLE_EXTENSIONS = {
    ".txt",
    ".md",
    ".py",
    ".js",
    ".ts",
    ".jsx",
    ".tsx",
    ".json",
    ".yaml",
    ".yml",
    ".html",
    ".css",
    ".java",
    ".go",
    ".rs",
    ".rb",
    ".sh",
    ".csv",
    ".sql",
    ".toml",
}

SKIP_FILENAMES = {
    "swampcastle.yaml",
    "swampcastle.yml",
    "swampcastle.yaml",
    "mempal.yml",
    ".gitignore",
    "package-lock.json",
}

CHUNK_SIZE = 800  # chars per drawer
CHUNK_OVERLAP = 100  # overlap between chunks
MIN_CHUNK_SIZE = 50  # skip tiny chunks
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB — skip files larger than this

# Heuristic thresholds
LONGEST_LINE_REJECT = 500  # unconditional reject if any line longer than this
WHITESPACE_RATIO_THRESHOLD = 0.05
AVG_LINE_LENGTH_THRESHOLD = 200
SYMBOL_TO_ALNUM_RATIO_THRESHOLD = 1.5

# Generated file signatures (small subset inspired by GitHub Linguist)
_HEADER_GENERATED_SIGNATURES = re.compile(
    r"(?im)^(?:\s*(?://|#|/\*+|\*)\s*)?(?:<auto-generated>|code generated by\b|@generated\b)"
)
_LICENSE_BANNER_SIGNATURE = re.compile(
    r"(?im)^\s*/\*![^\n]*for license information please see[^\n]*$"
)
_HEAD_TAIL_GENERATED_SIGNATURES = re.compile(r"(?i)sourceMappingURL=|webpackJsonp")

_MINIFIED_FILENAME_PATTERNS = (".min.js", ".min.css", ".bundle.js", ".map")


def _longest_line_length(content: str) -> int:
    return max((len(line) for line in content.splitlines()), default=0)


def _whitespace_ratio(content: str) -> float:
    if not content:
        return 1.0
    whitespace_chars = sum(1 for c in content if c.isspace())
    return whitespace_chars / len(content)


def _avg_line_length(content: str) -> float:
    lines = content.splitlines()
    if not lines:
        return 0.0
    return sum(len(line) for line in lines) / len(lines)


def _symbol_to_alnum_ratio(content: str) -> float:
    # ratio of symbol chars to alphanumeric chars
    alnum = sum(1 for c in content if c.isalnum())
    symbol = sum(1 for c in content if not c.isalnum() and not c.isspace())
    if alnum == 0:
        return float("inf") if symbol > 0 else 0.0
    return symbol / alnum


def _mining_rejection_reason(filepath: Path, content: str) -> str | None:
    """Return rejection reason when file looks too generated/dense to mine."""
    if content is None:
        return None

    longest_line = _longest_line_length(content)
    if longest_line > LONGEST_LINE_REJECT:
        return f"longest line {longest_line} > {LONGEST_LINE_REJECT}"

    name = filepath.name.lower()
    suffix = filepath.suffix.lower()

    for pat in _MINIFIED_FILENAME_PATTERNS:
        if name.endswith(pat):
            return f"filename matches {pat}"

    header = "\n".join(content.splitlines()[:3])
    head_tail = (content[:1000] + content[-1000:]) if len(content) > 2000 else content
    if _HEADER_GENERATED_SIGNATURES.search(header):
        return "generated header signature"
    if _LICENSE_BANNER_SIGNATURE.search(header):
        return "bundler license banner"
    if _HEAD_TAIL_GENERATED_SIGNATURES.search(head_tail):
        return "bundler/source map signature"

    if suffix == ".json":
        return None

    ws_ratio = _whitespace_ratio(content)
    if ws_ratio < WHITESPACE_RATIO_THRESHOLD:
        return f"whitespace ratio {ws_ratio:.3f} < {WHITESPACE_RATIO_THRESHOLD}"

    avg_line_length = _avg_line_length(content)
    if avg_line_length > AVG_LINE_LENGTH_THRESHOLD:
        return f"average line length {avg_line_length:.1f} > {AVG_LINE_LENGTH_THRESHOLD}"

    symbol_ratio = _symbol_to_alnum_ratio(content)
    if symbol_ratio > SYMBOL_TO_ALNUM_RATIO_THRESHOLD:
        return f"symbol/alnum ratio {symbol_ratio:.2f} > {SYMBOL_TO_ALNUM_RATIO_THRESHOLD}"

    return None


def is_probably_minified(filepath: Path, content: str) -> bool:
    """Return True when file looks minified/generated and should be skipped."""
    return _mining_rejection_reason(filepath, content) is not None


# =============================================================================
# IGNORE MATCHING
# =============================================================================


class GitignoreMatcher:
    """Lightweight matcher for one directory's .gitignore-like patterns."""

    def __init__(self, base_dir: Path, rules: list):
        self.base_dir = base_dir
        self.rules = rules

    @classmethod
    def _from_file(cls, dir_path: Path, filename: str):
        path = dir_path / filename
        if not path.is_file():
            return None

        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except Exception:
            return None

        rules = []
        for raw_line in lines:
            line = raw_line.strip()
            if not line:
                continue

            if line.startswith("\\#") or line.startswith("\\!"):
                line = line[1:]
            elif line.startswith("#"):
                continue

            negated = line.startswith("!")
            if negated:
                line = line[1:]

            anchored = line.startswith("/")
            if anchored:
                line = line.lstrip("/")

            dir_only = line.endswith("/")
            if dir_only:
                line = line.rstrip("/")

            if not line:
                continue

            rules.append(
                {
                    "pattern": line,
                    "anchored": anchored,
                    "dir_only": dir_only,
                    "negated": negated,
                }
            )

        if not rules:
            return None

        return cls(dir_path, rules)

    @classmethod
    def from_dir(cls, dir_path: Path):
        return cls._from_file(dir_path, ".gitignore")

    @classmethod
    def from_swampignore(cls, dir_path: Path):
        """Load .swampcastleignore (project-specific mining ignore)."""
        return cls._from_file(dir_path, ".swampcastleignore")

    def matches(self, path: Path, is_dir: bool = None):
        try:
            relative = path.relative_to(self.base_dir).as_posix().strip("/")
        except ValueError:
            return None

        if not relative:
            return None

        if is_dir is None:
            is_dir = path.is_dir()

        ignored = None
        for rule in self.rules:
            if self._rule_matches(rule, relative, is_dir):
                ignored = not rule["negated"]
        return ignored

    def _rule_matches(self, rule: dict, relative: str, is_dir: bool) -> bool:
        pattern = rule["pattern"]
        parts = relative.split("/")
        pattern_parts = pattern.split("/")

        if rule["dir_only"]:
            target_parts = parts if is_dir else parts[:-1]
            if not target_parts:
                return False
            if rule["anchored"] or len(pattern_parts) > 1:
                return self._match_from_root(target_parts, pattern_parts)
            return any(fnmatch.fnmatch(part, pattern) for part in target_parts)

        if rule["anchored"] or len(pattern_parts) > 1:
            return self._match_from_root(parts, pattern_parts)

        return any(fnmatch.fnmatch(part, pattern) for part in parts)

    def _match_from_root(self, target_parts: list, pattern_parts: list) -> bool:
        def matches(path_index: int, pattern_index: int) -> bool:
            if pattern_index == len(pattern_parts):
                return True

            if path_index == len(target_parts):
                return all(part == "**" for part in pattern_parts[pattern_index:])

            pattern_part = pattern_parts[pattern_index]
            if pattern_part == "**":
                return matches(path_index, pattern_index + 1) or matches(
                    path_index + 1, pattern_index
                )

            if not fnmatch.fnmatch(target_parts[path_index], pattern_part):
                return False

            return matches(path_index + 1, pattern_index + 1)

        return matches(0, 0)


def load_gitignore_matcher(dir_path: Path, cache: dict):
    """Load and cache one directory's .gitignore matcher."""
    if dir_path not in cache:
        cache[dir_path] = GitignoreMatcher.from_dir(dir_path)
    return cache[dir_path]


def load_swampignore_matcher(dir_path: Path, cache: dict):
    """Load and cache one directory's .swampcastleignore matcher."""
    if dir_path not in cache:
        cache[dir_path] = GitignoreMatcher.from_swampignore(dir_path)
    return cache[dir_path]


def _ignore_decision(path: Path, matchers: list, is_dir: bool = False) -> bool | None:
    """Return the last ignore decision for a path, or None when no rule matched."""
    decision = None
    for matcher in matchers:
        matched = matcher.matches(path, is_dir=is_dir)
        if matched is not None:
            decision = matched
    return decision


def is_gitignored(path: Path, matchers: list, is_dir: bool = False) -> bool:
    """Apply active .gitignore matchers in ancestor order; last match wins."""
    return _ignore_decision(path, matchers, is_dir=is_dir) is True


def is_swampignored(path: Path, matchers: list, is_dir: bool = False) -> bool:
    """Apply active .swampcastleignore matchers in ancestor order; last match wins."""
    return _ignore_decision(path, matchers, is_dir=is_dir) is True


def should_skip_dir(dirname: str) -> bool:
    """Skip known generated/cache directories before gitignore matching."""
    return dirname in SKIP_DIRS or dirname.endswith(".egg-info")


def normalize_include_paths(include_ignored: list) -> set:
    """Normalize comma-parsed include paths into project-relative POSIX strings."""
    normalized = set()
    for raw_path in include_ignored or []:
        candidate = str(raw_path).strip().strip("/")
        if candidate:
            normalized.add(Path(candidate).as_posix())
    return normalized


def is_exact_force_include(path: Path, project_path: Path, include_paths: set) -> bool:
    """Return True when a path exactly matches an explicit include override."""
    if not include_paths:
        return False

    try:
        relative = path.relative_to(project_path).as_posix().strip("/")
    except ValueError:
        return False

    return relative in include_paths


def is_force_included(path: Path, project_path: Path, include_paths: set) -> bool:
    """Return True when a path or one of its ancestors/descendants was explicitly included."""
    if not include_paths:
        return False

    try:
        relative = path.relative_to(project_path).as_posix().strip("/")
    except ValueError:
        return False

    if not relative:
        return False

    for include_path in include_paths:
        if relative == include_path:
            return True
        if relative.startswith(f"{include_path}/"):
            return True
        if include_path.startswith(f"{relative}/"):
            return True

    return False


# =============================================================================
# CONFIG
# =============================================================================


def load_config(project_dir: str) -> dict:
    """Load project-local mining config, migrating legacy filename if needed."""
    import yaml

    config_path = resolve_project_config(project_dir)
    if config_path is None:
        print(f"ERROR: No {PROJECT_CONFIG_NAME} found in {project_dir}")
        print(f"Run: swampcastle project {project_dir}")
        sys.exit(1)
    with open(config_path) as f:
        return yaml.safe_load(f)


# =============================================================================
# FILE ROUTING — which room does this file belong to?
# =============================================================================


def detect_room(filepath: Path, content: str, rooms: list, project_path: Path) -> str:
    """
    Route a file to the right room.
    Priority:
    1. Folder path matches a room name
    2. Filename matches a room name or keyword
    3. Content keyword scoring
    4. Fallback: "general"
    """
    relative = str(filepath.relative_to(project_path)).lower()
    filename = filepath.stem.lower()
    content_lower = content[:2000].lower()

    # Priority 1: folder path matches room name or keywords
    path_parts = relative.replace("\\", "/").split("/")
    for part in path_parts[:-1]:  # skip filename itself
        for room in rooms:
            candidates = [room["name"].lower()] + [k.lower() for k in room.get("keywords", [])]
            if any(part == c or c in part or part in c for c in candidates):
                return room["name"]

    # Priority 2: filename matches room name
    for room in rooms:
        if room["name"].lower() in filename or filename in room["name"].lower():
            return room["name"]

    # Priority 3: keyword scoring from room keywords + name
    scores = defaultdict(int)
    for room in rooms:
        keywords = room.get("keywords", []) + [room["name"]]
        for kw in keywords:
            count = content_lower.count(kw.lower())
            scores[room["name"]] += count

    if scores:
        best = max(scores, key=scores.get)
        if scores[best] > 0:
            return best

    return "general"


# =============================================================================
# CHUNKING
# =============================================================================


def _find_chunk_break(content: str, start: int, end: int) -> int:
    """Find the best chunk break <= end.

    Preference order (only if the boundary is in the back half of the window):
    1. paragraph boundary (\n\n)
    2. line boundary (\n)
    3. sentence boundary (. ! ? followed by whitespace/end)
    4. word boundary (space/tab)
    5. hard cut at end
    """
    min_break = start + CHUNK_SIZE // 2

    paragraph_pos = content.rfind("\n\n", start, end)
    if paragraph_pos >= min_break:
        return paragraph_pos

    newline_pos = content.rfind("\n", start, end)
    if newline_pos >= min_break:
        return newline_pos

    sentence_matches = list(re.finditer(r"[.!?](?=\s|$)", content[start:end]))
    if sentence_matches:
        sentence_pos = start + sentence_matches[-1].end()
        if sentence_pos >= min_break:
            return sentence_pos

    word_pos = max(content.rfind(" ", start, end), content.rfind("\t", start, end))
    if word_pos >= min_break:
        return word_pos

    return end


def chunk_text(content: str, source_file: str) -> list:
    """
    Split content into drawer-sized chunks.

    Preference order:
    - paragraph boundary
    - line boundary
    - sentence boundary
    - word boundary
    - hard cut at CHUNK_SIZE

    Returns list of {"content": str, "chunk_index": int}
    """
    content = content.strip()
    if not content:
        return []

    chunks = []
    start = 0
    chunk_index = 0

    while start < len(content):
        end = min(start + CHUNK_SIZE, len(content))
        if end < len(content):
            end = _find_chunk_break(content, start, end)

        chunk = content[start:end].strip()
        if len(chunk) >= MIN_CHUNK_SIZE:
            chunks.append({"content": chunk, "chunk_index": chunk_index})
            chunk_index += 1

        if end < len(content):
            next_start = max(0, end - CHUNK_OVERLAP)
            # Avoid starting the overlap in the middle of a word.
            if next_start > 0 and not content[next_start - 1].isspace():
                while next_start < len(content) and not content[next_start].isspace():
                    next_start += 1
                while next_start < len(content) and content[next_start].isspace():
                    next_start += 1
            start = next_start
        else:
            start = end

    return chunks


# =============================================================================
# PALACE — ChromaDB operations
# =============================================================================


class EmbeddingBuffer:
    """Buffer documents for batch embedding and bulk upsert.

    Uses resource-aware defaults. Flushes when batch_size or max_chars reached.
    """

    def __init__(self, collection, embedder=None, batch_size=None, max_chars=None):
        self.collection = collection
        self._docs = []
        self._ids = []
        self._metas = []
        self._chars = 0
        self._embedder = embedder
        self.stored_count = 0
        self._supports_embeddings = False
        try:
            sig = inspect.signature(collection.upsert)
            self._supports_embeddings = "embeddings" in sig.parameters
        except Exception:
            self._supports_embeddings = False

        # determine batch_size: explicit arg > env var > cpu-scaled default
        env_bs = os.environ.get("SWAMPCASTLE_EMBED_BATCH_SIZE")
        env_bs_v = None
        if env_bs:
            try:
                env_bs_v = int(env_bs)
            except (ValueError, TypeError):
                pass

        default_bs = suggest_onnx_tuning()["embed_batch_size"]
        self.batch_size = (
            batch_size
            if batch_size is not None
            else (env_bs_v if env_bs_v is not None else default_bs)
        )

        # determine max_chars: explicit arg > env var > default
        env_mc = os.environ.get("SWAMPCASTLE_EMBED_MAX_CHARS")
        env_mc_v = None
        if env_mc:
            try:
                env_mc_v = int(env_mc)
            except (ValueError, TypeError):
                pass
        self.max_chars = (
            max_chars
            if max_chars is not None
            else (env_mc_v if env_mc_v is not None else 2_000_000)
        )

    def add(self, document: str, id_: str, metadata: dict):
        self._docs.append(document)
        self._ids.append(id_)
        self._metas.append(metadata)
        self._chars += len(document)
        if self.batch_size > 0 and len(self._docs) >= self.batch_size:
            self.flush()
        elif self.max_chars > 0 and self._chars >= self.max_chars:
            self.flush()

    def flush(self) -> int:
        """Flush buffered documents to storage. Returns count stored. Propagates errors."""
        if not self._docs:
            return 0

        # resolve embedder
        embedder = self._embedder
        if embedder is None:
            embedder = getattr(self.collection, "_embedder", None)
        if embedder is None:
            from ..embeddings import get_embedder

            embedder = get_embedder()

        count = len(self._docs)
        texts = list(self._docs)
        ids = list(self._ids)
        metas = list(self._metas)

        # Embed first; if this raises, restore the buffer so the caller can retry
        # rather than silently discarding the documents.
        try:
            embeddings = embedder.embed(texts)
        except Exception:
            # Restore buffer — no data was written to storage
            self._docs = texts
            self._ids = ids
            self._metas = metas
            self._chars = sum(len(t) for t in texts)
            raise

        # Clear buffer before upsert: if upsert raises, the caller gets the
        # exception and the documents are intentionally not retried (the embedder
        # already ran; retrying would double-embed). Callers requiring durability
        # should implement their own retry with a fresh buffer.
        self._docs = []
        self._ids = []
        self._metas = []
        self._chars = 0

        if self._supports_embeddings:
            self.collection.upsert(documents=texts, ids=ids, metadatas=metas, embeddings=embeddings)
        else:
            # fallback: upsert without embeddings (backend will re-embed)
            self.collection.upsert(documents=texts, ids=ids, metadatas=metas)

        self.stored_count += count
        return count


def add_drawer(
    collection,
    wing: str,
    room: str,
    content: str,
    source_file: str,
    chunk_index: int,
    agent: str,
    contributor: str | None = None,
):
    """Add one drawer to the palace."""
    drawer_id = f"drawer_{wing}_{room}_{hashlib.sha256((source_file + str(chunk_index)).encode()).hexdigest()[:24]}"
    try:
        metadata = {
            "wing": wing,
            "room": room,
            "source_file": source_file,
            "chunk_index": chunk_index,
            "added_by": agent,
            "filed_at": datetime.now().isoformat(),
        }
        if contributor:
            metadata["contributor"] = contributor
        # Store file mtime so we can detect modifications later.
        try:
            metadata["source_mtime"] = os.path.getmtime(source_file)
        except OSError:
            pass
        collection.upsert(
            documents=[content],
            ids=[drawer_id],
            metadatas=[metadata],
        )
        return True
    except Exception:
        raise


def _delete_existing_file_drawers(collection, *, source_file: str, wing: str) -> None:
    """Delete existing drawers for one source file within one wing."""
    existing = collection.get(
        where={"$and": [{"source_file": source_file}, {"wing": wing}]},
        include=["metadatas"],
    )
    ids = existing.get("ids", [])
    if ids:
        collection.delete(ids=ids)


# =============================================================================
# PROCESS ONE FILE
# =============================================================================


def process_file(
    filepath: Path,
    project_path: Path,
    collection,
    wing: str,
    rooms: list,
    agent: str,
    dry_run: bool,
    team: list[str] | None = None,
    registry=None,
    verbose: bool = False,
    embed_buffer=None,
    force_no_skeleton: bool = False,
    _force_remine: bool = False,
) -> tuple:
    """Read, chunk, route, and file one file. Returns (drawer_count, room_name)."""

    # Skip if already filed
    source_file = str(filepath)
    if (
        not dry_run
        and not _force_remine
        and _file_already_mined(collection, source_file, wing=wing, check_mtime=True)
    ):
        return 0, None

    try:
        content = filepath.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return 0, None

    content = content.strip()
    skip_reason = _mining_rejection_reason(filepath, content)
    if skip_reason is not None:
        logger.debug("Skipping mined file %s: %s", filepath, skip_reason)
        if verbose:
            try:
                rel = filepath.relative_to(project_path)
            except Exception:
                rel = filepath
            print(f"  - SKIP {rel}: {skip_reason}")
        return 0, None

    if len(content) < MIN_CHUNK_SIZE:
        return 0, None

    room = detect_room(filepath, content, rooms, project_path)

    # Skeleton extraction for large files
    is_skeleton = False
    extractor = None
    # Trigger: lines > 2000 or size > 200KB
    if not force_no_skeleton and (content.count("\n") > 2000 or len(content) > 200_000):
        extractor = get_skeleton_extractor(source_file)

    if extractor:
        skeleton_content = extractor.extract(content)
        # Require at least 50% size reduction to justify storing as a skeleton;
        # anything less doesn't meaningfully compress and isn't worth deskeletonizing.
        if skeleton_content and len(skeleton_content) < len(content) * 0.5:
            content = skeleton_content
            is_skeleton = True

    chunks = chunk_text(content, source_file)

    contributor = detect_contributor(filepath, project_path, team=team, registry=registry)

    if dry_run:
        print(f"    [DRY RUN] {filepath.name} → room:{room} ({len(chunks)} drawers)")
        return len(chunks), room

    # Purge stale drawers for this file before re-inserting the fresh chunks.
    # Scope cleanup to the current wing so the same source file can be mined
    # into multiple wings without cross-wing deletion.
    _delete_existing_file_drawers(collection, source_file=source_file, wing=wing)

    drawers_added = 0
    for chunk in chunks:
        drawer_id = f"drawer_{wing}_{room}_{hashlib.sha256((source_file + str(chunk['chunk_index'])).encode()).hexdigest()[:24]}"
        metadata = {
            "wing": wing,
            "room": room,
            "source_file": source_file,
            "chunk_index": chunk["chunk_index"],
            "added_by": agent,
            "filed_at": datetime.now().isoformat(),
        }
        if is_skeleton:
            metadata["is_skeleton"] = True
        if contributor:
            metadata["contributor"] = contributor
        try:
            metadata["source_mtime"] = os.path.getmtime(source_file)
        except OSError:
            pass

        if embed_buffer is not None:
            embed_buffer.add(chunk["content"], drawer_id, metadata)
            drawers_added += 1
        else:
            added = add_drawer(
                collection=collection,
                wing=wing,
                room=room,
                content=chunk["content"],
                source_file=source_file,
                chunk_index=chunk["chunk_index"],
                agent=agent,
                contributor=contributor,
            )
            if added:
                drawers_added += 1

    return drawers_added, room


# =============================================================================
# SCAN PROJECT
# =============================================================================


def scan_project(
    project_dir: str,
    respect_gitignore: bool = True,
    include_ignored: list = None,
    only_force_included: bool = False,
) -> list:
    """Return list of all readable file paths."""
    project_path = Path(project_dir).expanduser().resolve()
    files = []
    active_matchers = []
    active_swamp_matchers = []
    matcher_cache = {}
    swamp_cache = {}
    include_paths = normalize_include_paths(include_ignored)

    if only_force_included and not include_paths:
        return []

    # load global ~/.swampcastleignore if present
    try:
        global_swamp = GitignoreMatcher.from_swampignore(Path.home())
    except Exception:
        global_swamp = None

    def _global_decision(path: Path, *, is_dir: bool) -> bool | None:
        """Return the global ~/.swampcastleignore decision, or None when no rule matched."""
        if global_swamp is None:
            return None
        try:
            relative = path.relative_to(project_path).as_posix().strip("/")
        except Exception:
            relative = path.name
        decision = None
        for rule in global_swamp.rules:
            try:
                if global_swamp._rule_matches(rule, relative, is_dir):
                    decision = not rule["negated"]
            except Exception:
                continue
        return decision

    def _is_ignored_by_precedence(path: Path, *, is_dir: bool) -> bool:
        """Apply project swampignore > global swampignore > gitignore precedence."""
        project_decision = _ignore_decision(path, active_swamp_matchers, is_dir=is_dir)
        if project_decision is not None:
            return project_decision

        global_decision = _global_decision(path, is_dir=is_dir)
        if global_decision is not None:
            return global_decision

        if respect_gitignore:
            return is_gitignored(path, active_matchers, is_dir=is_dir)
        return False

    for root, dirs, filenames in os.walk(project_path):
        root_path = Path(root)

        active_swamp_matchers = [
            matcher
            for matcher in active_swamp_matchers
            if root_path == matcher.base_dir or matcher.base_dir in root_path.parents
        ]
        current_swamp = load_swampignore_matcher(root_path, swamp_cache)
        if current_swamp is not None:
            active_swamp_matchers.append(current_swamp)

        if respect_gitignore:
            active_matchers = [
                matcher
                for matcher in active_matchers
                if root_path == matcher.base_dir or matcher.base_dir in root_path.parents
            ]
            current_matcher = load_gitignore_matcher(root_path, matcher_cache)
            if current_matcher is not None:
                active_matchers.append(current_matcher)

        dirs[:] = [
            d
            for d in dirs
            if is_force_included(root_path / d, project_path, include_paths)
            or not should_skip_dir(d)
        ]
        dirs[:] = [
            d
            for d in dirs
            if is_force_included(root_path / d, project_path, include_paths)
            or not _is_ignored_by_precedence(root_path / d, is_dir=True)
        ]

        for filename in filenames:
            filepath = root_path / filename
            force_include = is_force_included(filepath, project_path, include_paths)
            exact_force_include = is_exact_force_include(filepath, project_path, include_paths)

            if only_force_included and not force_include:
                continue

            if not force_include and filename in SKIP_FILENAMES:
                continue
            if filepath.suffix.lower() not in READABLE_EXTENSIONS and not exact_force_include:
                continue
            if not force_include and _is_ignored_by_precedence(filepath, is_dir=False):
                continue
            # Skip symlinks — prevents following links to /dev/urandom, etc.
            if filepath.is_symlink():
                continue
            # Skip files exceeding size limit
            try:
                if filepath.stat().st_size > MAX_FILE_SIZE:
                    continue
            except OSError:
                continue
            files.append(filepath)
    return files


# =============================================================================
# PARALLEL HELPERS
# =============================================================================

_MAX_PARALLEL_WORKERS = 32
_PARALLEL_WINDOW = 256  # max in-flight futures at once


def _resolve_parallel_workers(explicit: int | None) -> int | None:
    """Return worker count from explicit arg or env vars, or None for sequential."""
    if explicit is not None:
        if explicit <= 1:
            return None
        return min(explicit, _MAX_PARALLEL_WORKERS)
    if os.environ.get("SWAMPCASTLE_PARALLEL", "").lower() in ("1", "true", "yes"):
        raw = os.environ.get("SWAMPCASTLE_PARALLEL_WORKERS", "")
        try:
            count = int(raw) if raw else (os.cpu_count() or 2)
        except ValueError:
            count = os.cpu_count() or 2
        if count <= 1:
            return None
        return min(count, _MAX_PARALLEL_WORKERS)
    return None


def _process_file_worker(args):
    """Worker entry: read file, apply skeleton (if any), chunk and detect room.

    Accepts a single tuple argument (to be pickle-friendly) and returns a dict with
    keys: filepath, skipped (bool), skip_reason (str|None), chunks (list),
          room (str), is_skeleton (bool), verbose_skip (bool)
    """
    (filepath_str, project_dir_str, wing, rooms, force_no_skeleton, explain) = args
    filepath = Path(filepath_str)
    project_path = Path(project_dir_str)
    try:
        content = filepath.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {
            "filepath": filepath_str,
            "skipped": True,
            "skip_reason": "read_error",
            "verbose_skip": explain,
        }

    content = content.strip()
    if len(content) < MIN_CHUNK_SIZE:
        return {
            "filepath": filepath_str,
            "skipped": True,
            "skip_reason": "too_small",
            "verbose_skip": explain,
        }

    skip_reason = _mining_rejection_reason(filepath, content)
    if skip_reason is not None:
        return {
            "filepath": filepath_str,
            "skipped": True,
            "skip_reason": skip_reason,
            "verbose_skip": explain,
        }

    room = detect_room(filepath, content, rooms, project_path)

    is_skeleton = False
    extractor = None
    if not force_no_skeleton and (content.count("\n") > 2000 or len(content) > 200_000):
        extractor = get_skeleton_extractor(str(filepath))

    if extractor:
        skeleton_content = extractor.extract(content)
        if skeleton_content and len(skeleton_content) < len(content) * 0.5:
            content = skeleton_content
            is_skeleton = True

    chunks = chunk_text(content, str(filepath))
    return {
        "filepath": filepath_str,
        "skipped": False,
        "skip_reason": None,
        "chunks": chunks,
        "room": room,
        "is_skeleton": is_skeleton,
        "verbose_skip": False,
    }


# =============================================================================
# MAIN: MINE
# =============================================================================


def mine(  # noqa: C901
    project_dir: str,
    palace_path: str,
    wing: str = None,
    agent: str = "swampcastle",
    limit: int = 0,
    dry_run: bool = False,
    respect_gitignore: bool = True,
    include_ignored: list = None,
    storage_factory: StorageFactory | None = None,
    explain: bool = False,
    force_no_skeleton: bool = False,
    only_force_included: bool = False,
    extract_kg_proposals: bool = False,
    embed_batch_size: int | None = None,
    _force_remine: bool = False,
    parallel_workers: int | None = None,
):
    """Mine a project directory into the palace."""

    project_path = Path(project_dir).expanduser().resolve()
    config = load_config(project_dir)

    wing = wing or config["wing"]
    rooms = config.get("rooms", [{"name": "general", "description": "All project files"}])
    team = config.get("team")

    # Load entity registry for contributor resolution (best-effort)
    registry = None
    if team:
        try:
            from ..entity_registry import EntityRegistry

            registry = EntityRegistry.load()
        except Exception:
            pass

    files = scan_project(
        project_dir,
        respect_gitignore=respect_gitignore,
        include_ignored=include_ignored,
        only_force_included=only_force_included,
    )
    if limit > 0:
        files = files[:limit]

    print(f"\n{'=' * 55}")
    print("  SwampCastle Mine")
    print(f"{'=' * 55}")
    print(f"  Wing:    {wing}")
    print(f"  Rooms:   {', '.join(r['name'] for r in rooms)}")
    print(f"  Files:   {len(files)}")
    print(f"  Palace:  {palace_path}")
    if dry_run:
        print("  DRY RUN — nothing will be filed")
    if not respect_gitignore:
        print("  .gitignore: DISABLED")
    if include_ignored:
        print(f"  Include: {', '.join(sorted(normalize_include_paths(include_ignored)))}")
    print(f"{'─' * 55}\n")

    if not dry_run:
        if storage_factory is None:
            settings = CastleSettings(castle_path=palace_path, _env_file=None)
            storage_factory = factory_from_settings(settings)
        collection = storage_factory.open_collection("swampcastle_chests")
        # prepare embedding buffer
        embedder = getattr(storage_factory, "_embedder", None)
        embed_buffer = EmbeddingBuffer(
            collection,
            embedder=embedder,
            batch_size=embed_batch_size,
        )
    else:
        collection = None
        embed_buffer = None

    total_drawers = 0
    files_skipped = 0
    room_counts = defaultdict(int)

    max_workers = _resolve_parallel_workers(parallel_workers)

    if max_workers is None:
        # Sequential path — original behaviour, unchanged
        for i, filepath in enumerate(files, 1):
            drawers, room = process_file(
                filepath=filepath,
                project_path=project_path,
                collection=collection,
                wing=wing,
                rooms=rooms,
                agent=agent,
                dry_run=dry_run,
                team=team,
                registry=registry,
                verbose=explain,
                embed_buffer=embed_buffer,
                force_no_skeleton=force_no_skeleton,
                _force_remine=_force_remine,
            )
            if drawers == 0:
                if not dry_run:
                    files_skipped += 1
                continue

            total_drawers += drawers
            room_counts[room] += 1
            if not dry_run:
                print(f"  ✓ [{i:4}/{len(files)}] {filepath.name[:50]:50} +{drawers}")
    else:
        # Parallel path — workers handle I/O + chunking; consumer handles all storage writes.
        # A sliding window of _PARALLEL_WINDOW futures bounds peak memory on large repos.
        submit_count = 0
        completed = 0

        def _submittable_args(fp: Path) -> tuple | None:
            """Return worker args for fp, or None if the file should be skipped."""
            if not dry_run:
                if not _force_remine and _file_already_mined(
                    collection, str(fp), wing=wing, check_mtime=True
                ):
                    return None
            return (str(fp), str(project_path), wing, rooms, force_no_skeleton, explain)

        def _consume(res: dict, source_filepath: Path) -> tuple[int, int]:
            """Consume one worker result. Returns (drawers_added, skipped_delta)."""
            filepath_str = res["filepath"]

            if res["skipped"]:
                if dry_run and res["verbose_skip"]:
                    try:
                        rel = source_filepath.relative_to(project_path)
                    except ValueError:
                        rel = source_filepath
                    print(f"  - SKIP {rel}: {res['skip_reason']}")
                return 0, (0 if dry_run else 1)

            chunks = res["chunks"]
            room = res["room"]
            is_skeleton = res["is_skeleton"]

            if dry_run:
                print(f"    [DRY RUN] {source_filepath.name} → room:{room} ({len(chunks)} drawers)")
                room_counts[room] += 1
                return len(chunks), 0

            _delete_existing_file_drawers(collection, source_file=filepath_str, wing=wing)
            contributor = detect_contributor(
                source_filepath, project_path, team=team, registry=registry
            )

            try:
                source_mtime: float | None = os.path.getmtime(filepath_str)
            except OSError:
                source_mtime = None

            drawers_added = 0
            for chunk in chunks:
                drawer_id = f"drawer_{wing}_{room}_{hashlib.sha256((filepath_str + str(chunk['chunk_index'])).encode()).hexdigest()[:24]}"
                metadata = {
                    "wing": wing,
                    "room": room,
                    "source_file": filepath_str,
                    "chunk_index": chunk["chunk_index"],
                    "added_by": agent,
                    "filed_at": datetime.now().isoformat(),
                }
                if is_skeleton:
                    metadata["is_skeleton"] = True
                if contributor:
                    metadata["contributor"] = contributor
                if source_mtime is not None:
                    metadata["source_mtime"] = source_mtime

                if embed_buffer is not None:
                    embed_buffer.add(chunk["content"], drawer_id, metadata)
                    drawers_added += 1
                else:
                    if add_drawer(
                        collection=collection,
                        wing=wing,
                        room=room,
                        content=chunk["content"],
                        source_file=filepath_str,
                        chunk_index=chunk["chunk_index"],
                        agent=agent,
                        contributor=contributor,
                    ):
                        drawers_added += 1

            room_counts[room] += 1
            return drawers_added, 0

        files_iter = iter(files)
        in_flight: dict = {}

        spawn_context = multiprocessing.get_context("spawn")

        with ProcessPoolExecutor(max_workers=max_workers, mp_context=spawn_context) as ex:
            # Prime the window
            for fp in files_iter:
                worker_args = _submittable_args(fp)
                if worker_args is None:
                    files_skipped += 1
                    continue
                fut = ex.submit(_process_file_worker, worker_args)
                in_flight[fut] = fp
                submit_count += 1
                if len(in_flight) >= _PARALLEL_WINDOW:
                    break

            while in_flight:
                done_fut = next(as_completed(in_flight))
                source_fp = in_flight.pop(done_fut)
                completed += 1

                try:
                    res = done_fut.result()
                except BrokenProcessPool:
                    raise
                except Exception as e:
                    logger.warning("Worker failed for %s: %s", source_fp, e)
                    if not dry_run:
                        files_skipped += 1
                    res = None

                if res is not None:
                    added, skipped_delta = _consume(res, source_fp)
                    total_drawers += added
                    files_skipped += skipped_delta
                    if not dry_run and added > 0:
                        print(
                            f"  ✓ [{completed:4}/{submit_count}] {source_fp.name[:50]:50} +{added}"
                        )

                # Slide the window: submit one more for each completion
                for fp in files_iter:
                    worker_args = _submittable_args(fp)
                    if worker_args is None:
                        files_skipped += 1
                        continue
                    fut = ex.submit(_process_file_worker, worker_args)
                    in_flight[fut] = fp
                    submit_count += 1
                    break  # one submission per completion to keep window size stable

    # flush any remaining buffered embeddings; update total from actual stored count
    if embed_buffer is not None:
        embed_buffer.flush()
        total_drawers = embed_buffer.stored_count

    extracted_candidates = 0
    if (
        extract_kg_proposals
        and not dry_run
        and storage_factory is not None
        and collection is not None
    ):
        extracted_candidates = persist_kg_proposals_for_wing(
            palace_path=palace_path,
            storage_factory=storage_factory,
            collection=collection,
            wing=wing,
        )

    print(f"\n{'=' * 55}")
    print("  Done.")
    print(f"  Files processed: {len(files) - files_skipped}")
    print(f"  Files skipped (already filed): {files_skipped}")
    print(f"  Drawers filed: {total_drawers}")
    if extract_kg_proposals:
        if dry_run:
            print("  KG proposal extraction: skipped (dry run)")
        else:
            print(f"  KG candidate triples: {extracted_candidates}")
    print("\n  By room:")
    for room, count in sorted(room_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"    {room:20} {count} files")
    print('\n  Next: swampcastle search "what you\'re looking for"')
    print(f"{'=' * 55}\n")


# =============================================================================
# STATUS
# =============================================================================


def status(palace_path: str):
    """Show what's been filed in the palace."""
    try:
        settings = CastleSettings(castle_path=palace_path, _env_file=None)
        factory = factory_from_settings(settings)
        col = factory.open_collection("swampcastle_chests")
        if col.count() == 0:
            raise Exception("Empty palace")
    except Exception:
        print(f"\n  No palace found at {palace_path}")
        print("  Run: swampcastle build <dir> then swampcastle gather <dir>")
        return

    # Count by wing and room using paginated scans so large castles are not truncated.
    total = col.count()
    wing_rooms = defaultdict(lambda: defaultdict(int))
    offset = 0
    batch_size = 1000

    while offset < max(total, 1):
        batch = col.get(limit=batch_size, offset=offset, include=["metadatas"])
        ids = batch.get("ids", [])
        if not ids:
            break
        for m in batch.get("metadatas", []):
            wing_rooms[m.get("wing", "?")][m.get("room", "?")] += 1
        offset += len(ids)

    print(f"\n{'=' * 55}")
    print(f"  SwampCastle Status — {total} drawers")
    print(f"{'=' * 55}\n")
    for wing, rooms in sorted(wing_rooms.items()):
        print(f"  WING: {wing}")
        for room, count in sorted(rooms.items(), key=lambda x: x[1], reverse=True):
            print(f"    ROOM: {room:20} {count:5} drawers")
        print()
    print(f"{'=' * 55}\n")
