import logging
from pathlib import Path

from swampcastle.mining import miner


def test_reject_long_line_unconditional():
    content = "a" * 501 + "\nrest"
    assert miner.is_probably_minified(Path("foo.js"), content) is True


def test_json_not_rejected_by_whitespace_heuristic():
    content = '{"key":"' + ("x" * 100) + '"}\n'
    assert miner.is_probably_minified(Path("data.json"), content) is False


def test_minified_js_rejected_by_whitespace():
    content = "".join(["var a=0;" for _ in range(200)])
    assert miner.is_probably_minified(Path("app.js"), content) is True


def test_bundler_license_banner_rejected():
    content = "/*! For license information please see app.js.LICENSE.txt */\n(()=>{})();"
    assert miner.is_probably_minified(Path("bundle.js"), content) is True


def test_generated_header_rejected():
    content = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"
    assert miner.is_probably_minified(Path("api.pb.go"), content) is True


def test_plain_license_reference_not_rejected():
    content = (
        "/* For license information please see LICENSE.txt. */\n"
        "export function normalizeUser(user) {\n"
        "    return { ...user, isActive: Boolean(user.isActive) };\n"
        "}\n"
    )
    assert miner.is_probably_minified(Path("utils.js"), content) is False


def test_plain_do_not_edit_comment_not_rejected():
    content = (
        "# Do not edit database defaults below without updating deployment docs.\n"
        'DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3"}}\n'
        "DEBUG = False\n"
    )
    assert miner.is_probably_minified(Path("settings.py"), content) is False


def test_minified_filename_rejected():
    content = "function good() { return 1 }\n" * 20
    assert miner.is_probably_minified(Path("app.min.js"), content) is True


def test_symbol_ratio_rejects_obfuscated_js():
    content = "\n".join(["[] + ![] + !![] + ({})[[]] + ({}+[]) ;" for _ in range(30)])
    assert miner.is_probably_minified(Path("obfuscated.js"), content) is True


def test_symbol_ratio_does_not_reject_sql_schema_fixture():
    content = """
CREATE TABLE "user_roles" (
    "user_id" INTEGER NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
    "role_id" INTEGER NOT NULL REFERENCES "roles" ("id") ON DELETE CASCADE,
    PRIMARY KEY ("user_id", "role_id")
);

CREATE INDEX "user_roles_user_id_idx" ON "user_roles" ("user_id");
""".strip()
    assert miner.is_probably_minified(Path("schema.sql"), content) is False


def test_process_file_logs_skip_reason_for_rejected_file(caplog, tmp_path):
    filepath = tmp_path / "app.min.js"
    filepath.write_text("function good() { return 1; }\n" * 5, encoding="utf-8")

    caplog.set_level(logging.DEBUG, logger="swampcastle.mining.miner")
    drawers, room = miner.process_file(
        filepath=filepath,
        project_path=tmp_path,
        collection=None,
        wing="demo",
        rooms=[{"name": "general"}],
        agent="swampcastle",
        dry_run=False,
    )

    assert (drawers, room) == (0, None)
    assert "Skipping mined file" in caplog.text
    assert "filename matches .min.js" in caplog.text
