"""
hooks_install.py — Install SwampCastle ingest hooks into Claude Code and pi.

Three artifacts, all regenerated on every run (safe to re-run):

  1. ~/.swampcastle/hooks/swampcastle-hook.sh — the launcher every hook goes
     through, implementing the pipx-aware resolution ladder from the packaging
     decision: SWAMPCASTLE_PYTHON override → console script on PATH → the
     conventional pipx location → shebang-derived interpreter → python3 probe.
  2. ~/.claude/settings.json — SessionStart + SessionEnd + PreCompact hook
     entries pointing at the launcher (merged in; other settings and hooks
     are preserved). SessionStart injects the status digest as
     additionalContext on startup|resume|clear|compact.
  3. ~/.pi/agent/extensions/swampcastle-hooks.ts — auto-discovered pi
     extension: ingest on session_shutdown/session_compact, digest injection
     via session_start + before_agent_start.
"""

import json
from pathlib import Path

WRAPPER_SCRIPT = """\
#!/usr/bin/env bash
# SwampCastle hook launcher — pipx-aware resolution ladder.
# For pass-through hooks (session-end, precompact) it answers the harness
# instantly and detaches the real work: hook grace at session end is short,
# and a cancelled hook's process group is reaped — an un-detached ingest
# child dies with it (observed: Claude Code "Hook cancelled" killed the
# SessionEnd mine).
# Regenerated by `swampcastle install-hooks`; do not edit.
set -u
export SWAMPCASTLE_INTERNAL=1

RUNNER=()
# 1. Explicit override always wins.
if [ -n "${SWAMPCASTLE_PYTHON:-}" ] && [ -x "${SWAMPCASTLE_PYTHON:-}" ]; then
    RUNNER=("$SWAMPCASTLE_PYTHON" -m swampcastle)
# 2. Console script on PATH (pipx and uv tool both provide one).
elif command -v swampcastle >/dev/null 2>&1; then
    RUNNER=(swampcastle)
# 3. Conventional pipx location (hooks often run with a stripped PATH).
elif [ -x "$HOME/.local/bin/swampcastle" ]; then
    RUNNER=("$HOME/.local/bin/swampcastle")
else
    # 4. Derive the interpreter from the console-script shebang. Accept only
    #    executable python* basenames — an `#!/usr/bin/env python` wrapper
    #    yields `env` here and is skipped.
    script="$HOME/.local/bin/swampcastle"
    if [ -r "$script" ]; then
        shebang="$(sed -n '1p' "$script" 2>/dev/null)"
        case "$shebang" in
            '#!'*)
                interp="${shebang#\\#!}"
                interp="${interp# }"
                interp="${interp%% *}"
                case "${interp##*/}" in
                    python*)
                        if [ -x "$interp" ]; then
                            RUNNER=("$interp" -m swampcastle)
                        fi
                        ;;
                esac
                ;;
        esac
    fi
    # 5. Last resort: any python3 that can import the package.
    if [ ${#RUNNER[@]} -eq 0 ] && command -v python3 >/dev/null 2>&1 \\
        && python3 -c "import swampcastle" >/dev/null 2>&1; then
        RUNNER=(python3 -m swampcastle)
    fi
fi

case " $* " in
    *" session-end "*|*" precompact "*)
        # Pass-through hooks: the answer is always {}. Say so immediately,
        # then hand the payload to a fully detached runner (new session via
        # setsid, disowned) so client shutdown cannot reap it.
        payload="$(cat 2>/dev/null || true)"
        printf '{}\\n'
        if [ ${#RUNNER[@]} -gt 0 ]; then
            logdir="$HOME/.swampcastle/hook_state"
            mkdir -p "$logdir" 2>/dev/null || true
            printf '%s' "$payload" | setsid "${RUNNER[@]}" hook run "$@" \\
                >>"$logdir/hook.log" 2>&1 &
            disown
        fi
        exit 0
        ;;
esac

# Decision-carrying hooks (stop, session-start) run synchronously — the
# harness consumes their output.
if [ ${#RUNNER[@]} -gt 0 ]; then
    exec "${RUNNER[@]}" hook run "$@"
fi

echo "swampcastle hook error: no runnable swampcastle found" >&2
exit 1
"""

PI_EXTENSION_TEMPLATE = """\
/**
 * SwampCastle hooks for pi.
 * Regenerated by `swampcastle install-hooks`; do not edit.
 *
 * Ingest (fire-and-forget): pipes {{session_id, transcript_path}} into the
 * SwampCastle hook launcher on session_shutdown / session_compact.
 *
 * Digest injection: pi has no SessionStart additionalContext analogue, so the
 * extension runs the same session-start hook (cached digest; a cold cache
 * builds synchronously) at session_start and injects the result as a
 * persistent message on the first before_agent_start.
 */
import {{ spawn }} from "node:child_process";

const WRAPPER = {wrapper_json};

function fetchDigest(): Promise<string | null> {{
    return new Promise((resolve) => {{
        try {{
            const child = spawn(WRAPPER, ["--hook", "session-start", "--harness", "pi"], {{
                stdio: ["pipe", "pipe", "ignore"],
            }});
            let out = "";
            child.stdout?.on("data", (chunk: any) => {{
                out += chunk;
            }});
            child.on("error", () => resolve(null));
            child.on("close", () => {{
                try {{
                    const parsed = JSON.parse(out);
                    resolve(parsed?.hookSpecificOutput?.additionalContext ?? null);
                }} catch {{
                    resolve(null);
                }}
            }});
            child.stdin?.write(JSON.stringify({{ session_id: "pi", cwd: process.cwd() }}));
            child.stdin?.end();
        }} catch {{
            resolve(null);
        }}
    }});
}}

export default function swampcastleHooks(pi: any) {{
    let digestPromise: Promise<string | null> = Promise.resolve(null);
    let digestInjected = false;

    pi.on("session_start", () => {{
        digestPromise = fetchDigest();
        digestInjected = false;
    }});

    pi.on("before_agent_start", async () => {{
        if (digestInjected) return;
        digestInjected = true;
        const digest = await digestPromise;
        if (!digest) return;
        return {{
            message: {{
                customType: "swampcastle-digest",
                content: digest,
                display: false,
            }},
        }};
    }});

    const ingest = (ctx: any) => {{
        try {{
            const file = ctx?.sessionManager?.getSessionFile?.();
            if (!file) return;
            const payload = JSON.stringify({{
                session_id: "pi",
                transcript_path: file,
            }});
            const child = spawn(WRAPPER, ["--hook", "session-end", "--harness", "pi"], {{
                detached: true,
                stdio: ["pipe", "ignore", "ignore"],
            }});
            child.on("error", () => {{}});
            child.stdin?.write(payload);
            child.stdin?.end();
            child.unref();
        }} catch {{
            // never break the harness
        }}
    }};
    pi.on("session_shutdown", (_event: any, ctx: any) => ingest(ctx));
    pi.on("session_compact", (_event: any, ctx: any) => ingest(ctx));
}}
"""

# Claude Code hook events wired to hooks_cli hook names. A matcher scopes
# the event sources the hook fires for (None = all).
CLAUDE_HOOK_EVENTS = {
    "SessionEnd": {"hook": "session-end", "matcher": None},
    "PreCompact": {"hook": "precompact", "matcher": None},
    # Digest injection on every context reset, including post-compact.
    "SessionStart": {"hook": "session-start", "matcher": "startup|resume|clear|compact"},
}


def install_wrapper(hooks_dir=None) -> Path:
    """Write the launcher script and mark it executable."""
    if hooks_dir is None:
        hooks_dir = Path.home() / ".swampcastle" / "hooks"
    hooks_dir = Path(hooks_dir)
    hooks_dir.mkdir(parents=True, exist_ok=True)
    path = hooks_dir / "swampcastle-hook.sh"
    path.write_text(WRAPPER_SCRIPT)
    path.chmod(path.stat().st_mode | 0o755)
    return path


def install_claude_hooks(settings_path=None, wrapper_path=None) -> bool:
    """Merge SessionEnd/PreCompact hook entries into Claude Code settings.

    Returns True if the file changed. Existing hooks and settings survive.
    """
    if settings_path is None:
        settings_path = Path.home() / ".claude" / "settings.json"
    settings_path = Path(settings_path)

    data = {}
    if settings_path.is_file():
        try:
            data = json.loads(settings_path.read_text())
        except (json.JSONDecodeError, OSError):
            raise RuntimeError(f"Refusing to rewrite unparseable {settings_path}")

    hooks = data.setdefault("hooks", {})
    changed = False
    for event, spec in CLAUDE_HOOK_EVENTS.items():
        command = f"{wrapper_path} --hook {spec['hook']} --harness claude-code"
        entries = hooks.setdefault(event, [])
        existing = [h.get("command", "") for e in entries for h in e.get("hooks", [])]
        if any(str(wrapper_path) in c for c in existing):
            continue
        entry = {"hooks": [{"type": "command", "command": command}]}
        if spec["matcher"]:
            entry["matcher"] = spec["matcher"]
        entries.append(entry)
        changed = True

    if changed:
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        settings_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    return changed


def install_pi_extension(extensions_dir=None, wrapper_path=None) -> Path:
    """Write the auto-discovered pi extension pointing at the launcher."""
    if extensions_dir is None:
        extensions_dir = Path.home() / ".pi" / "agent" / "extensions"
    extensions_dir = Path(extensions_dir)
    extensions_dir.mkdir(parents=True, exist_ok=True)
    path = extensions_dir / "swampcastle-hooks.ts"
    path.write_text(PI_EXTENSION_TEMPLATE.format(wrapper_json=json.dumps(str(wrapper_path))))
    return path


def install_all() -> dict:
    """Install launcher + both clients' hooks at their real locations."""
    wrapper = install_wrapper()
    claude_changed = install_claude_hooks(wrapper_path=wrapper)
    pi_path = install_pi_extension(wrapper_path=wrapper)
    return {
        "wrapper": wrapper,
        "claude_settings_changed": claude_changed,
        "pi_extension": pi_path,
    }
